import logging
from time import time


if __name__ == '__main__':
    start_time = time()

    console_formatter = logging.Formatter('%(asctime)s : %(name)s :: %(levelname)s : %(message)s')
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(console_formatter)
    console_handler.setLevel(logging.INFO)
    logger.addHandler(console_handler)

    logger.info('started')

    allowed_domains = [
        # 'blog.feedspot.com',
        'dedrone.com',
        'droneblog.com',
        'dronefly.com',
        # 'dronelife.com',
        # 'en.wikipedia.org',
        'nationalinterest.org',
        # 'racing.dronelife.com',
        # 'www.feedspot.com',
        'www.linkedin.com',
        'www.suasnews.com',
        # 'rotordronemag.com',
        # 'thedronenews.com',
        'www.reddit.com',
        'www.dcmilitary.com',
        'cftni.org',
        'www.military.com',
        'www.washingtonpost.com',
        'www.c4isrnet.com',
        'www.defenseone.com',
        'www.cnbc.com',
        'tools.wmflabs.org',
        'thebulletin.org',
        'web.archive.org',
        'dx.doi.org',
        'www.faa.gov',
        'www.defense.gov',
        'www.congress.gov',
        'jrupprechtlaw.com',
        'www.auvsi.org',
        'afwerxdc.org',
        'www.newamerica.org',
        'doi.org',
        'www.technologyreview.com',
        # 'www.wsj.com',
        'www.army-technology.com',
        'www.wired.com',
        'www.janes.com',
        'tati-uas.com',
        'defense-update.com',
        'www.aviationweek.com',
        'www.globalsecurity.org',
        'www.defenseindustrydaily.com',
        'www.nytimes.com',
        'warisboring.com',
        'www.thedrive.com',
        'breakingdefense.com',
        'gizmodo.com',
        'motherboard.vice.com',
        'defensesystems.com',
        'electronica-submarina.com',
        'iz.ru',
        'news.usni.org',
        'www.airforce-technology.com',
        'www.brookings.edu',
        # 'www.cnn.com',
        'www.hrw.org',
        'www.lockheedmartin.com',
        'www.navysbir.com',
        'www.navweaps.com',
        'www.rand.org',
        'www.realcleardefense.com',
        'www.airforce-technology.com',
        'www.worldcat.org',
        'www.aspistrategist.org.au',
        'www.cnas.org',
        'foreignpolicy.com',
        'www.defensenews.com',
        'thediplomat.com',
        'www.flightglobal.com',
        'www.strategypage.com',
        'rt.com',
        'english.yonhapnews.co.kr',
        'www.arminfo.am',
        'www.israeldefense.co.il',
        'www.bellingcat.com',
        'www.wilsoncenter.org',
        'www.dawn.com',
        'arquivo.pt',
        'www.israel.org',
        'counterterrorism.newamerica.net',
        'www.un.org',
        'longreads.tni.org',
        'www.pewresearch.org',
        'www.armyrecognition.com',
        'taskandpurpose.com',
        'www.armytimes.com',
        'sbir.defensebusiness.org',
        'www.theatlantic.com',
        'www.pakistanbodycount.org',
        'www.smallarmsreview.com',
        'www.smallarmssolutions.com',
        'www.nellis.af.mil',
        'medium.com',
        'scholar.google.com',
        'www.leoaffairs.com',
        'www.jstor.org',
        'popularmilitary.com',
        'www.cia.gov',
        'aviationweek.com',
        'defence-blog.com',
        'www.thedailybeast.com',
        'www.militarynews.ir',
        'www.centcom.mil',
        'www.webcitation.org',
        'www.latimes.com',
        'www.newsweek.com',
        'www.usatoday.com',
        'www.cbsnews.com',
        'investigatons.nbcnews.com',
        'articles.latimes.com',
        'www.npr.org',
        'www.salon.com',
        'dronewarsuk.wordpress.com',
        'www.rollingstone.com',
        'www.gq.com',
        'www.people-press.org',
        'www.bbc.co.uk',
        'www.popsci.com',
        'www.pewglobal.org',
        'madsciblog.tradoc.army.mil',
        'www.icrc.org',
        'www.navy.mil',
        'www.businessinsider.com',
        'www.dia.mil',
        'www.aclu.org',
        'www.thestatesman.net',
        'www.forbes.com',
        'thehill.com',
        'www.reuters.com',
        'www.dw.com',
        'www.politico.com',
        'www.state.gov',
        'www.axios.com',
        'www.tacticalreport.com',
        'www.bloombergquint.com',
        'www.sfgate.com',
        'www.lawfareblog.com',
        'purl.fdlp.gov',
        'www.foreignaffairs.com',
        'viaf.org',
        'www.defenddemocracy.org',
        'www.pbs.org',
        'dronenetwork.com',
        'english.peopledaily.com.cn',
        'www.ft.com',
        'www.presstv.com',
        'www.iranfocus.com',
        'en.klimov.ru',
        'armyrecognition.com',
        'www.ainonline.com',
        'www.eurospike.com',
        'time.com',
        'www.rferl.org',
        'www.bloomberg.com',
        'www.haaretz.com',
        'www.abc.net.au',
        'www.defenceweb.co.za',
        'www.upi.com',
        'www.arabnews.com',
        'www.thenews.com.pk',
        'www.oxfordislamicstudies.com',
        'www.airforceworld.com',
        'arstechnica.com'

    ]

    allowed_domains = set(allowed_domains)
    allowed_domains = list(allowed_domains)
    logger.info(sorted(allowed_domains))

    logger.info('done')

    finish_time = time()
    elapsed_hours, elapsed_remainder = divmod(finish_time - start_time, 3600)
    elapsed_minutes, elapsed_seconds = divmod(elapsed_remainder, 60)
    logger.info('Time: {:0>2}:{:0>2}:{:05.2f}'.format(int(elapsed_hours), int(elapsed_minutes), elapsed_seconds))
    console_handler.close()
    logger.removeHandler(console_handler)
